### ISSUE TITLE
About the understanding of transform

### ISSUE THREAD

**Issue by hellojialee** [anatolix/keras_Realtime_Multi-Person_Pose_Estimation#16]
Could you please explain this lline?
https://github.com/anatolix/keras_Realtime_Multi-Person_Pose_Estimation/blob/new-generation/py_rmpe_server/py_rmpe_transformer.py#L47

config.transform_params.target_dist / scale_self * self.scale
I don't understand why "self.scale" is used in "A = self.scale * cos(self.degree / 180. * pi )". And dose the "target_dist" control the occupation of the people in the whole picture? Many many thanks and thanks again for your great project!

**Comment by anatolix** [comment]
pers["scale_provided"] = img_anns[p]["bbox"][3] / 368 
i.e. scale_self=height/368

this mean  this config.transform_params.target_dist / scale_self * self.scale is equal to 
0.6 / (height/368) * self.scale
or (0.6*368)/height * self.scale.
368 is size of training picture.

This mean we will scale picture so height of person always will be 0.6 of picture.
After it we apply random scaling (self.scale) from 0.6 to 1.1

**Comment by hellojialee** [comment]
Yes, I have got your point! We center, resize and crop according the the main person, but there may be some other persons' keypoints on the same image or groundtruth map. Thus, other persons' joints may be cropped. Is this the situation which you noted as a "TODO"? 
So, do you agree that we can simply judge the coordinates of these joints are within the range of 368*368 and change the visibility value of such special joints.

**Comment by Ai-is-light** [comment]
@anatolix , in your coco_metric.py code 
input_img = np.transpose(np.float32(imageToTest_padded[:, :, :, np.newaxis]),
                                 (3, 0, 1, 2))  # required shape (1, width, height, channels)
but , in the caffe/author's code,
net.blobs['data'].reshape(*(1, 3, imageToTest_padded.shape[0], imageToTest_padded.shape[1]))
    #net.forward() # dry run
    net.blobs['data'].data[...] = np.transpose(np.float32(imageToTest_padded[:,:,:,np.newaxis]), (3,2,0,1))/256 - 0.5;

and, in your code, there is not the (3,2,0,1))/256 - 0.5, this is the reason that in Keras, the framework can rescale the values in the (0,1], yeah, you know, I'm using caffe but not similar with the Keras. Thanks

**Comment by anatolix** [comment]
this is not exactly my code, but transpose looks correct for me.
