### ISSUE TITLE
Where is a new version of generate_hdf5.py

### ISSUE THREAD

**Issue by beebrain** [anatolix/keras_Realtime_Multi-Person_Pose_Estimation#17]
Thank you for your code.
I have some question. I followed your instruction.
"re-generate val_dataset.h5 with new version of generate_hdf5.py (will be backward compatible, just one attribute 'meta' added)", but I did not find generate_hdf5.py in training folder or you mean.
Please give more information.
Thank you.

**Comment by piperod** [comment]
Are you sure you are in the master branch?

**Comment by beebrain** [comment]
@piperod Thak you. It's  my bad. Now I cloned the master branch. 
So I have some question, I must run generate_mask.py before execute generate_hdf5.py, correct?

**Comment by anatolix** [comment]
I've changed main branch to new generation, if you in new branch generate_mask and generate_hdf5 merged to one program.

**Comment by beebrain** [comment]
@anatolix, that is a coco_mark.py , right?

**Comment by anatolix** [comment]
https://github.com/anatolix/keras_Realtime_Multi-Person_Pose_Estimation/blob/new-generation/training/coco_masks_hdf5.py

**Comment by beebrain** [comment]
@anatolix Thank you, now i am training the model from your code.
