### ISSUE TITLE
The difference between 'coco_metric.py' and 'inhouse_metric.py'. 

### ISSUE THREAD

**Issue by hellojialee** [anatolix/keras_Realtime_Multi-Person_Pose_Estimation#22]
Which is the evaluation standard in MScoco keypoint detection challenge 2017?
It seems that the coco python api is different from the procedure in Chapter 2.2. Evaluation Framework which is explained in:
Benchmarking and Error Diagnosis in Multi-Instance Pose Estimation [https://arxiv.org/abs/1707.05388](url)

**Comment by anatolix** [comment]
ihhouse is our own metric, not compatible with anything. Can't say anything about Benchmarking paper
