### ISSUE TITLE
How can I use the same implementation for a single person 2D pose estimation? 

### ISSUE THREAD

**Issue by abinjoabraham** [anatolix/keras_Realtime_Multi-Person_Pose_Estimation#27]
@anatolix First of all thanks a lot for your work. When I compare with the michalfaber code I find this one more simple. Being a new guy to this field of artificial intelligence this implementation will be a lot helpful for me for the future references. Can I modify the same implementation to detect the pose for a single person rather than the multiperson?

**Comment by murrayLuke** [comment]
This should work with one person as well as multiple people.

**Comment by abinjoabraham** [comment]
@murrayLuke Thanks for your input. I understand that this will work for single person as well. But was just thinking whether I can reduce the training set data so that it need to work only for the single person. By this way I can easily create a smaller version which I can train it in my mac book pro 2017 edition with no nVidea GPU. :)

**Comment by anatolix** [comment]
Imho no chance you could train it without GPU.

**Comment by abinjoabraham** [comment]
Sorry for this lame question. Finally after going through some papers and implementations I finally think that the same can be done with only the heat maps. And the response time also will be better for single person as the weights will be less for the same as we reduce the complexity of the system.

**Comment by abinjoabraham** [comment]
Hence I am closing this question. Thanks for your valuable time in replying to this question.
