### ISSUE TITLE
The generation of PAF

### ISSUE THREAD

**Issue by hellojialee** [anatolix/keras_Realtime_Multi-Person_Pose_Estimation#29]
Should we uncomment the TODO code of the following lines? 
`        # TODO: check it again
        # basically we should use center of grid, but in this place classic implementation uses left-top point.
        # self.X = self.X + stride / 2 - 0.5
        # self.Y = self.Y + stride / 2 - 0.5`

[https://github.com/anatolix/keras_Realtime_Multi-Person_Pose_Estimation/blob/new-generation/py_rmpe_server/py_rmpe_heatmapper.py#L29](url)

**Comment by anatolix** [comment]
This is currently implemented like in C++  code. You could try, but my opinion that 
1. nothing will change, NN just adapts
2. you have to update inference code as well.
