### ISSUE TITLE
docker: Cannot connect to the Docker daemon on mac

### ISSUE THREAD

**Issue by sri123098** [anatolix/keras_Realtime_Multi-Person_Pose_Estimation#33]
Dear all,
I'm getting the following error on mac.
~/PycharmProjects/RBG/keras_Realtime_Multi-Person_Pose_Estimation$ docker run -v [/Users/sriramreddy/PycharmProjects/RBG/keras_Realtime_Multi-Person_Pose_Estimation]:/workspace -it bvlc/caffe:cpu python dump_caffe_layers.py
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.

Could you please help me to fix this issue ?

Thanks,
Sriram

**Comment by anatolix** [comment]
I've not using docker in this project. Looks like your docker is just not running

**Comment by sri123098** [comment]
Can I run without using docker ?
I need to train the model on the given coco data set.
Could you please help me whether I can go ahead without using docker for environment?

**Comment by anatolix** [comment]
I've never tested it on mac, imho better just to use Linux, you could use VMWare or any other VM for that
