### ISSUE TITLE
About the transform

### ISSUE THREAD

**Issue by hellojialee** [anatolix/keras_Realtime_Multi-Person_Pose_Estimation#36]
Does the self.scale is redundant in this line of code:
` A = self.scale * cos(self.degree / 180. * pi )`
[https://github.com/anatolix/keras_Realtime_Multi-Person_Pose_Estimation/blob/8ac3229444128ef6a64be35106d5111c7f0e8fb5/py_rmpe_server/py_rmpe_transformer.py#L44](url)

And if we change the scale_prob  = 0, will the performance improve?
`self.scale_prob = 1  # TODO: this is actually scale unprobability, i.e. 1 = off, 0 = always, not sure if it is a bug or not
`

**Comment by anatolix** [comment]
> And if we change the scale_prob = 0, will the performance improve?

no it will not we do all augmentation with one affine transformation with fixed cost.
i.e. it already improved to near the limit
