### ISSUE TITLE
Parameters for get_testing_model() to load model in demo_image.py

### ISSUE THREAD

**Issue by ChintanTrivedi** [anatolix/keras_Realtime_Multi-Person_Pose_Estimation#38]
What arguments to pass for `np_branch1, np_branch2` in `model = get_testing_model() ` line 247 of demo_image.py?

I tried passing the `stageT_branch1_out, stageT_branch2_out` parameters like in demo.ipynb but I run into the error "ValueError: Shapes must be equal rank, but are 0 and 4".

Thanks!

**Comment by dimitree54** [comment]
I as well faced this problem. Hope my comment will help someone. I also looked through demo.ipynb and found out, that parameters  np_branch1=38, np_branch2=19 will be working.
