### ISSUE TITLE
get_testing_model() missing 2 required positional arguments at line 247

### ISSUE THREAD

**Issue by ghost** [anatolix/keras_Realtime_Multi-Person_Pose_Estimation#40]
Traceback (most recent call last):
  File "demo_image.py", line 247, in <module>
    model = get_testing_model()
TypeError: get_testing_model() missing 2 required positional arguments: 'np_branch1' and 'np_branch2'.

**Comment by abinjoabraham** [comment]
@Carbonil The same can be taken from the michalfaber model where this arguments are already defined.

**Comment by ghost** [comment]
oh thanks@abinjoabraham
