### ISSUE TITLE
can not retrain using multi-gpu mode?

### ISSUE THREAD

**Issue by Minotaur-CN** [anatolix/keras_Realtime_Multi-Person_Pose_Estimation#6]
Hi, anatolix
ValueError: You are trying to load a weight file containing 1 layers into a model with 92 layers.

The same error happens in demo_image.py when evaluate the model performance.

**Comment by anatolix** [comment]
This weights file produces by multigpu training? Looks like it saved/loaded incorrectly too. 
Short answer multigpu training in keras is unusable state yet.

**Comment by Minotaur-CN** [comment]
Yes, the weights file produces by multi-gpu training, and can not load correctly now.
Thanks for your work!
