### ISSUE TITLE
What's the function of mapIdx ?

### ISSUE THREAD

**Issue by USTClj** [anatolix/keras_Realtime_Multi-Person_Pose_Estimation#7]
Hi~ I have some doubt about the code. Dose the limbSeq defies the connection between keypoints? An other issue is that what's the function of mapIdx?

mapIdx = [[31,32], [39,40], [33,34], [35,36], [41,42], [43,44], [19,20], [21,22], \
          [23,24], [25,26], [27,28], [29,30], [47,48], [49,50], [53,54], [51,52], \
          [55,56], [37,38], [45,46]]
Hoping for your help.
Regards!

**Comment by anatolix** [comment]
That is not limbs connections, you could notice pairs always [N,N+1], it issome PAF x/y indexes, where did you found it i thought i removed everything like this from this fork, see config.py to look like how this numbers calculated

**Comment by USTClj** [comment]
@anatolix Could you explain it a litter more specific? I did not get your point...

**Comment by anatolix** [comment]
1. Get this file(it is in brach "new-generation")
https://github.com/anatolix/keras_Realtime_Multi-Person_Pose_Estimation/blob/new-generation/config.py
This file calculates layers

2. Run it as a program, you will get layer map, it looks like this.
```
{0: 'neck->Rhip:x',
 1: 'neck->Rhip:y',
 2: 'Rhip->Rkne:x',
 3: 'Rhip->Rkne:y',
 4: 'Rkne->Rank:x',
 5: 'Rkne->Rank:y',
 6: 'neck->Lhip:x',
 7: 'neck->Lhip:y',
 8: 'Lhip->Lkne:x',
 9: 'Lhip->Lkne:y',
 10: 'Lkne->Lank:x',
 11: 'Lkne->Lank:y',
 12: 'neck->Rsho:x',
 13: 'neck->Rsho:y',
 14: 'Rsho->Relb:x',
 15: 'Rsho->Relb:y',
 16: 'Relb->Rwri:x',
 17: 'Relb->Rwri:y',
 18: 'Rsho->Rear:x',
 19: 'Rsho->Rear:y',
 20: 'neck->Lsho:x',
 21: 'neck->Lsho:y',
 22: 'Lsho->Lelb:x',
 23: 'Lsho->Lelb:y',
 24: 'Lelb->Lwri:x',
 25: 'Lelb->Lwri:y',
 26: 'Lsho->Lear:x',
 26: 'Lsho->Lear:x',
 27: 'Lsho->Lear:y',
 28: 'neck->nose:x',
 29: 'neck->nose:y',
 30: 'nose->Reye:x',
 31: 'nose->Reye:y',
 32: 'nose->Leye:x',
 33: 'nose->Leye:y',
 34: 'Reye->Rear:x',
 35: 'Reye->Rear:y',
 36: 'Leye->Lear:x',
 37: 'Leye->Lear:y',
 38: 'nose',
 39: 'neck',
 40: 'Rsho',
 41: 'Relb',
 42: 'Rwri',
 43: 'Lsho',
 44: 'Lelb',
 45: 'Lwri',
 46: 'Rhip',
 47: 'Rkne',
 48: 'Rank',
 49: 'Lhip',
 50: 'Lkne',
 51: 'Lank',
 52: 'Reye',
 53: 'Leye',
 54: 'Rear',
 55: 'Lear',
 56: 'background'}
```

3. Check the number against mapIdx and you will know what it means.

4. File calculates layer map from text strings, read the code if you want to understand mechanics.

**Comment by USTClj** [comment]
@anatolix Thank you for your kind help！
