### ISSUE TITLE
How to undersatand the criterion？

### ISSUE THREAD

**Issue by USTClj** [anatolix/keras_Realtime_Multi-Person_Pose_Estimation#8]
in demo.ipynb：

`score_midpts = np.multiply(vec_x, vec[0]) + np.multiply(vec_y, vec[1])
                
                score_with_dist_prior = sum(score_midpts)/len(score_midpts) \
                                        + min(0.5*oriImg.shape[0]/norm-1, 0)
                
                criterion1 = len(np.nonzero(score_midpts > param['thre2'])[0]) > 0.8 * len(score_midpts)
                # parm['thre2'] = 0.05
                criterion2 = score_with_dist_prior > 0
                if criterion1 and criterion2:
                    connection_candidate.append([i, j, score_with_dist_prior, 
                                                 score_with_dist_prior+candA[i][2]+candB[j][2]])`

How to understand the value of “min(0.5*oriImg.shape[0]/norm-1, 0)”？  The tow probability terms are added directly.  And how to understand the two criterion？？

**Comment by anatolix** [comment]
this looks like notebook code, better ask author at https://github.com/michalfaber/keras_Realtime_Multi-Person_Pose_Estimation, i haven't read it yet

**Comment by USTClj** [comment]
Thank you for your advice！

**Comment by USTClj** [comment]
@anatolix  Oh, btw, where is the PAFs generation code preparing the training data?

**Comment by anatolix** [comment]
https://github.com/anatolix/keras_Realtime_Multi-Person_Pose_Estimation/blob/new-generation/py_rmpe_server/py_rmpe_heatmapper.py

**Comment by USTClj** [comment]
@anatolix OK,  Thanks！ 
What's the use of      stride/2-0.5 ？
https://github.com/anatolix/keras_Realtime_Multi-Person_Pose_Estimation/blob/new-generation/py_rmpe_server/py_rmpe_heatmapper.py/#24](url)
