### ISSUE TITLE
Is it ab bug？ visible = joints[:,i,2] < 2

### ISSUE THREAD

**Issue by USTClj** [anatolix/keras_Realtime_Multi-Person_Pose_Estimation#9]
In coco, v=2 represents “labelled , visible”

**Comment by anatolix** [comment]
No it is not. Our encoding is different.
check COCOSourceConfig.convert here:
https://github.com/anatolix/keras_Realtime_Multi-Person_Pose_Estimation/blob/new-generation/config.py
